# 0. change name
name: Alma Linux 8 
#
on:
  push:
    branches: [ master ]
    paths:
    - 'alma8/**'
    - '.trigger/**'
    - '.github/workflows/alma8.yml'
  pull_request:
    branches: [ master ]
#    
jobs:
# change job name
  alma8:
    runs-on: ubuntu-22.04
    env:
        # change the following 4 variables
        DOCKER_FILE: alma8/Dockerfile 
        DOCKER_ACCOUNT: jeonghanlee
        DOCKER_REPO: alma8-epics
        DOCKER_TAG: v2.2.0
        
    steps:
      - 
        name: checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ github.workspace }}/${{ env.DOCKER_FILE }}
          push: ${{ github.event_name != 'pull_request' }}
          #tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          
