
name: CentOS7


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  centos7:
    runs-on: ubuntu-latest
    env:
        OS_NAME: centos7
        DOCKER_ACCOUNT: alscontrols
        DOCKER_REPO: ${{ env.OS_NAME }}-epics

    steps:
      - 
        name: checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            $${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ github.workspace }}/$OS_NAME/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          #tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ env.DOCKER_ACCOUNT }}/${{ env.DOCKER_REPO }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          
