---
name: Debian 13 Trixie

"on":
  push:
    branches: [master]
    paths:
      - "debian13/**"
      - "gate.bash"
      - ".trigger/**"
      - ".github/workflows/debian13.yml"
      - ".github/workflows/image.yml"
  pull_request:
    branches: [master]
    paths:
      - "debian13/**"
      - "gate.bash"
      - ".github/workflows/debian13.yml"
      - ".github/workflows/image.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  debian13:
    uses: ./.github/workflows/image.yml
    with:
      image_dir: debian13
      image_name: jeonghanlee/debian13-epics
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
