name: ci

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]
    
jobs:
  debian10:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./debian10
          push: true
          tags: ${username}/debian10-epics:latest

      - 
        name : Image Digest
        run: echo ${{ steps.docker_builder.output.digest }}
