---
name: Rocky Linux 10.2

"on":
  push:
    branches: [master]
    paths:
      - "rocky10/**"
      - "gate.bash"
      - ".trigger/**"
      - ".github/workflows/rocky10.yml"
      - ".github/workflows/image.yml"
  pull_request:
    branches: [master]
    paths:
      - "rocky10/**"
      - "gate.bash"
      - ".github/workflows/rocky10.yml"
      - ".github/workflows/image.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  rocky10:
    uses: ./.github/workflows/image.yml
    with:
      image_dir: rocky10
      image_name: jeonghanlee/rocky10-epics
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
