---
name: Rocky Linux 9

"on":
  push:
    branches: [master]
    paths:
      - "rocky9/**"
      - ".trigger/**"
      - ".github/workflows/rocky9.yml"
  pull_request:
    branches: [master]
    paths:
      - "rocky9/**"
      - ".github/workflows/rocky9.yml"

permissions:
  contents: read

jobs:
  rocky9:
    runs-on: ubuntu-22.04
    env:
      IMAGE_CONTEXT: rocky9
      DOCKER_FILE: rocky9/Dockerfile
      DOCKER_IMAGE: jeonghanlee/rocky9-epics
      DOCKER_TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v7
        with:
          context: ${{ github.workspace }}/${{ env.IMAGE_CONTEXT }}
          file: ${{ github.workspace }}/${{ env.DOCKER_FILE }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
