---
name: Rocky Linux 8.10

"on":
  push:
    branches: [master]
    paths:
      - "rocky8/**"
      - "gate.bash"
      - ".trigger/**"
      - ".github/workflows/rocky8.yml"
      - ".github/workflows/image.yml"
  pull_request:
    branches: [master]
    paths:
      - "rocky8/**"
      - "gate.bash"
      - ".github/workflows/rocky8.yml"
      - ".github/workflows/image.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  rocky8:
    uses: ./.github/workflows/image.yml
    with:
      image_dir: rocky8
      image_name: jeonghanlee/rocky8-epics
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
