---
name: Ubuntu 26.04 EPICS runner

"on":
  push:
    branches: [master]
    paths:
      - "ubuntu26-epics-runner/**"
      - "gate.bash"
      - ".trigger/**"
      - ".github/workflows/ubuntu26-epics-runner.yml"
      - ".github/workflows/image.yml"
  pull_request:
    branches: [master]
    paths:
      - "ubuntu26-epics-runner/**"
      - "gate.bash"
      - ".github/workflows/ubuntu26-epics-runner.yml"
      - ".github/workflows/image.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ubuntu26-epics-runner:
    uses: ./.github/workflows/image.yml
    with:
      image_dir: ubuntu26-epics-runner
      image_name: jeonghanlee/ubuntu26-epics-runner
      is_runner: true
