---
name: Ubuntu 24.04 Noble

"on":
  push:
    branches: [master]
    paths:
      - "ubuntu24/**"
      - "gate.bash"
      - ".trigger/**"
      - ".github/workflows/ubuntu24.yml"
      - ".github/workflows/image.yml"
  pull_request:
    branches: [master]
    paths:
      - "ubuntu24/**"
      - "gate.bash"
      - ".github/workflows/ubuntu24.yml"
      - ".github/workflows/image.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ubuntu24:
    uses: ./.github/workflows/image.yml
    with:
      image_dir: ubuntu24
      image_name: jeonghanlee/ubuntu24-epics
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
